"""
Pydantic v2 request/response models for the FastAPI application.

Keep all input/output schemas here so they are easy to extend.
"""
from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Shared
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    status: str = "ok"
    version: str = "1.0.0"


# ---------------------------------------------------------------------------
# Chat  (/chat)
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    question: str = Field(..., min_length=1, description="User's question or message.")
    history: list[dict[str, str]] = Field(
        default_factory=list,
        description="Prior conversation turns, each {'role': ..., 'content': ...}.",
    )


class ChatResponse(BaseModel):
    answer: str
    model: str


# ---------------------------------------------------------------------------
# RAG  (/rag/query  &  /rag/ingest)
# ---------------------------------------------------------------------------

class RAGRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Question to answer from the knowledge base.")
    k: int = Field(default=4, ge=1, le=10, description="Number of documents to retrieve.")


class RAGSource(BaseModel):
    title: str
    source: str
    document_type: str
    snippet: str


class RAGResponse(BaseModel):
    answer: str
    sources: list[RAGSource]


class IngestRequest(BaseModel):
    """Body for POST /rag/ingest.

    Provide exactly one of ``url`` or ``text``.
    """
    url: Optional[str] = Field(None, description="Public URL to fetch and ingest.")
    text: Optional[str] = Field(None, description="Raw text to ingest directly.")
    title: str = Field("Untitled", description="Human-readable title stored as metadata.")
    source: str = Field("", description="Source label stored as metadata.")
    chunk_size: int = Field(500, ge=50, le=5000, description="Characters per chunk.")
    chunk_overlap: int = Field(50, ge=0, le=500, description="Overlap between consecutive chunks.")

    @model_validator(mode="after")
    def _require_url_or_text(self) -> "IngestRequest":
        if not self.url and not self.text:
            raise ValueError("Provide either 'url' or 'text'.")
        return self


class IngestResponse(BaseModel):
    chunks_added: int
    collection: str
    message: str = "OK"


# ---------------------------------------------------------------------------
# Agent  (/agent/run)
# ---------------------------------------------------------------------------

class AgentRequest(BaseModel):
    query: str = Field(..., min_length=1, description="Task or question for the ReAct agent.")


class AgentStep(BaseModel):
    tool: str
    tool_input: Any
    observation: str


class AgentResponse(BaseModel):
    output: str
    steps: list[AgentStep]


# ---------------------------------------------------------------------------
# Notion Revision  (/notion/revise)
# ---------------------------------------------------------------------------

class RevisionRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        description="Natural language query, e.g. 'what did I learn on Monday?'",
    )


class RevisionResponse(BaseModel):
    date: str = Field(description="Resolved date in YYYY-MM-DD format.")
    pages_found: int = Field(description="Number of Notion pages retrieved for that date.")
    summary: str = Field(description="LLM-generated markdown revision summary.")


# ---------------------------------------------------------------------------
# Socratic Quiz  (/notion/quiz)
# ---------------------------------------------------------------------------

class QuizStartRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        description="Natural language query, e.g. 'test me on yesterday's notes'",
    )


class QuizStartResponse(BaseModel):
    session_id: str = Field(description="Unique ID for this quiz session.")
    date: str = Field(description="Resolved date in YYYY-MM-DD format.")
    pages_found: int = Field(description="Number of Notion pages retrieved for that date.")
    question: str = Field(description="The first quiz question generated by the LLM.")


class QuizAnswerRequest(BaseModel):
    answer: str = Field(..., min_length=1, description="User's answer to the current question.")


class QuizAnswerResponse(BaseModel):
    evaluation: str = Field(description="Feedback on the user's answer.")
    is_completed: bool = Field(description="True if the quiz is finished.")
    next_question: Optional[str] = Field(None, description="The next question, if not completed.")


# ---------------------------------------------------------------------------
# Progress Tracker  (/notion/progress)
# ---------------------------------------------------------------------------

class WeakConcept(BaseModel):
    concept: str = Field(description="The name of the concept or topic.")
    count: int = Field(description="Number of times the user struggled with this concept.")
    gap_description: str = Field(description="Explanation of the specific gap revealed by the user's answers. Distinguish between strengths and weaknesses if applicable.")
    severity: int = Field(description="Severity score for this gap, from 0 (no gap/strength) to 5 (critical).", ge=0, le=5)


class StructuredProgressReport(BaseModel):
    weak_concepts: list[WeakConcept] = Field(description="List of concepts the user struggled with, ranked by severity or count.")
    revision_suggestions: list[str] = Field(description="Actionable suggestions for revision.")


class ProgressResponse(BaseModel):
    sessions_analysed: int = Field(description="Number of distinct quiz sessions in history.")
    total_qa_pairs: int = Field(description="Total Q&A pairs stored across all sessions.")
    weak_qa_pairs: int = Field(description="Number of Q&A pairs where the answer was incorrect.")
    report: StructuredProgressReport = Field(description="Structured report of knowledge gaps and revision suggestions.")
